In [5]:
import numpy as np 
import matplotlib.pyplot as plt
from public_tests import *


In [7]:
from utilss import *

In [8]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [12]:
print(X_train[:5])
print(type(X_train))

[[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
<class 'numpy.ndarray'>


In [15]:
print(y_train[:5])
print(type(y_train))

[1 1 0 0 1]
<class 'numpy.ndarray'>


In [17]:
print(X_train.shape, y_train.shape, len(X_train))

(10, 3) (10,) 10


In [28]:
def compute_entropy(y):
    entropy = 0
    m = X_train.shape

    if len(y) != 0:
        p1 = len(y[y == 1]) / len(y)

        if p1 != 0 and p1 != 1:
            entropy = -p1 * np.log2(p1) - (1 - p1) * np.log2(1 - p1)
        else:
            entropy = 0
    
    print(p1)
    return entropy




In [30]:
print("Entropy at root node: ", compute_entropy(y_train))

compute_entropy_test(compute_entropy)

0.5
Entropy at root node:  1.0
1.0
0.0
0.5
0.6666666666666666
0.3333333333333333
0.6666666666666666
 All tests passed.
